# Generated by Django 5.0.4 on 2024-07-14 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0003_alter_artist_artist_image'),
        ('gender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=255)),
                ('album_release', models.CharField(max_length=4)),
                ('album_description', models.TextField()),
                ('album_link', models.TextField(blank=True, null=True)),
                ('album_image', models.ImageField(upload_to='media/album_images')),
                ('album_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_artist', to='artist.artist')),
                ('album_gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_album', to='gender.gender')),
            ],
        ),
    ]
