# Generated by Django 5.0.4 on 2024-07-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_image',
            field=models.ImageField(upload_to='album_images'),
        ),
    ]
