# Generated by Django 5.0.4 on 2024-07-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
